title: 'Retro Rewind Podcast'
default_lang: en
author:
  name: 'Francisco X. Ruiz'
  email: feedback@retrorewindpodcast.com
taxonomies:
  - decadeType
  - genre
  - rateClassic
  - rateNostalgic
  - rateTragic
  - hosts
  - finalRating
  - faveEp
  - category
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects:
  patreon: patreon.com/retrorewindpodcast
routes:
  /110: /episodes/aladdin-podcast
  /109: /episodes/spacecamp-podcast
  /108: /episodes/mortal-kombat-podcast
  /107: /episodes/city-slickers-podcast
  /106: /episodes/the-boy-who-could-fly-podcast
  /105: /episodes/lotr-the-fellowship-of-the-ring-podcast
  /104: /episodes/sneakers-podcast
  /103: /episodes/jaws-podcast
  /102: /episodes/waynes-world-podcast
  /101: /episodes/santa-claus-the-movie-podcast
  /100: /episodes/goldeneye-podcast
  /99: /episodes/young-frankenstein-podcast
  /98: /episodes/the-x-files-fight-the-future-podcast
  /97: /episodes/adventures-in-babysitting-podcast
  /96: /episodes/predator-podcast
  /95: /episodes/ferris-buellers-day-off-podcast
  /94: /episodes/the-truman-show-podcast
  /93: /episodes/the-breakfast-club-podcast
  /92: /episodes/bust-a-move-2-podcast
  /91: /episodes/the-rock-podcast
  /90: /episodes/terminator-2-judgment-day-podcast
  /89: /episodes/the-terminator-podcast
  /88: /episodes/what-about-bob-podcast
  /87: /episodes/son-in-law-podcast
  /86: /episodes/wargames-podcast
  /85: /episodes/team-fortress-classic-podcast
  /84: /episodes/jumanji-podcast
  /83: /episodes/stay-tuned-podcast
  /82: /episodes/a-few-good-men-podcast
  /81: /episodes/uncle-buck-podcast
  /80: /episodes/the-jerk-podcast
  /79: /episodes/star-wars-original-trilogy-podcast
  /78: /episodes/super-street-fighter-2-podcast
  /77: /episodes/back-to-the-future-3-podcast
  /76: /episodes/the-rescuers-down-under-podcast
  /75: /episodes/major-payne
  /74: /episodes/back-to-the-future-2-podcast
  /73: /episodes/groundhog-day-podcast
  /72: /episodes/an-american-tail-podcast
  /71: /episodes/home-alone-podcast
  /70: /episodes/back-to-the-future-podcast
  /69: /episodes/e-t-the-extra-terrestrial-podcast
  /68: /episodes/a-goofy-movie-podcast
  /67: /episodes/encino-man-podcast
  /66: /episodes/a-league-of-their-own-podcast
  /65: /episodes/cant-hardly-wait-podcast
  /64: /episodes/super-star-wars-podcast
  /63: /episodes/three-men-and-a-baby-podcast
  /62: /episodes/the-land-before-time-podcast
  /61: /episodes/short-circuit-podcast
  /60: /episodes/pee-wee-s-big-adventure-podcast
  /59: /episodes/sonic-the-hedgehog-2-podcast
  /58: /episodes/twister-podcast
  /57: /episodes/batman-podcast
  /56: /episodes/the-mighty-ducks-podcast
  /55: /episodes/the-wizard-podcast
  /54: /episodes/true-lies-podcast
  /53: /episodes/three-amigos-podcast
  /52: /episodes/spaceballs-podcast
  /51: /episodes/bill-and-teds-excellent-adventure-podcast
  /50: /episodes/dumb-and-dumber-podcast
  /49: /episodes/star-fox-64-podcast
  /48: /episodes/the-sixth-sense-podcast
  /47: /episodes/stargate-podcast
  /46: /episodes/peter-pan-podcast
  /45: /episodes/swiss-family-robinson-podcast
  /44: /episodes/beverly-hills-ninja-podcast
  /43: /episodes/teenage-mutant-ninja-turtles-podcast
  /42: /episodes/angels-in-the-outfield-podcast
  /41: /episodes/the-muppet-movie-podcast
  /40: /episodes/donkey-kong-country-podcast
  /39: /episodes/speed-podcast
  /38: /episodes/maverick-podcast
  /37: /episodes/ace-ventura-pet-detective-podcast
  /36: /episodes/sister-act-podcast
  /35: /episodes/who-framed-roger-rabbit-podcast
  /34: /episodes/f-zero-podcast
  /33: /episodes/romancing-the-stone-podcast
  /32: /episodes/cool-runnings-podcast
  /31: /episodes/the-cutting-edge-podcast
  /30: /episodes/the-great-mouse-detective-podcast
  /29: /episodes/the-mask-of-zorro-podcast
  /28: /episodes/mary-poppins-podcast
  /27: /episodes/super-mario-world-podcast
  /26: /episodes/monty-python-and-the-holy-grail-podcast
  /25: /episodes/robin-hood-prince-of-thieves-podcast
  /24: /episodes/the-last-starfighter-podcast
  /23: /episodes/tremors-podcast
  /22: /episodes/the-neverending-story-podcast
  /21: /episodes/apollo-13-podcast
  /20: /episodes/the-karate-kid-podcast
  /19: /episodes/duck-tales-the-movie-podcast
  /18: /episodes/teenage-mutant-ninja-turtles-arcade-game-podcast
  /17: /episodes/explorers-podcast
  /16: /episodes/independence-day-podcast
  /15: /episodes/the-fifth-element-podcast
  /14: /episodes/honey-i-shrunk-the-kids-podcast
  /13: /episodes/labyrinth-podcast
  /12: /episodes/star-trek-iv-the-voyage-home-podcast
  /11: /episodes/super-mario-kart-podcast
  /10: /episodes/mission-impossible-podcast
  /9: /episodes/batteries-not-included-podcast
  /8: /episodes/return-to-oz-podcast
  /7: /episodes/anne-of-green-gables-podcast
  /6: /episodes/super-mario-bros-podcast
  /5: /episodes/mega-man-x-podcast
  /4: /episodes/flight-of-the-navigator-podcast
  /3: /episodes/masters-of-the-universe-podcast
  /2: /episodes/the-rocketeer-podcast
  /1: /episodes/superman-3-podcast
blog:
  route: /blog
